# Generated by Django 6.0.6 on 2026-06-12 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('optimistic_time', models.FloatField(default=0)),
                ('most_likely_time', models.FloatField(default=0)),
                ('pessimistic_time', models.FloatField(default=0)),
                ('expected_duration', models.FloatField(default=0, editable=False)),
                ('variance', models.FloatField(default=0, editable=False)),
                ('standard_deviation', models.FloatField(default=0, editable=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('earliest_start', models.FloatField(default=0, editable=False)),
                ('earliest_finish', models.FloatField(default=0, editable=False)),
                ('latest_start', models.FloatField(default=0, editable=False)),
                ('latest_finish', models.FloatField(default=0, editable=False)),
                ('float_time', models.FloatField(default=0, editable=False)),
                ('is_critical', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['project', 'earliest_start'],
            },
        ),
        migrations.CreateModel(
            name='WBSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='activities.wbsitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'WBS Item',
                'verbose_name_plural': 'WBS Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='activities.activity')),
                ('predecessor_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='activities.activity')),
            ],
            options={
                'verbose_name_plural': 'Dependencies',
                'unique_together': {('activity', 'predecessor_activity')},
            },
        ),
    ]
